FROM node:12 as builder

# 노드수정
# 작업 폴더를 만들고 npm 설치
WORKDIR /app

#RUN npm i -g npm 

RUN rm /usr/local/bin/yarn
RUN rm /usr/local/bin/yarnpkg && npm install -g yarn

#RUN npm install -g yarn

#RUN rm yarn.lock
#RUN rm package-lock.json

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

RUN yarn

COPY . /app
RUN yarn build:stg

FROM nginx:1.13.9-alpine
# nginx의 기본 설정을 삭제하고 앱에서 ㅛㅁ구설정한 파일을 복사
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /app/build /usr/share/nginx/html

# 80포트 오픈하고 nginx 실행
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]