FROM node:12-alpine as builder

# 작업 폴더를 만들고 npm 설치
WORKDIR /app
ADD . /app/

RUN npm i -g npm 

RUN rm /usr/local/bin/yarn
RUN rm /usr/local/bin/yarnpkg && npm install -g yarn

#npm i -g yarn

RUN rm yarn.lock
RUN rm package-lock.json
RUN yarn
RUN yarn build:stg



FROM nginx:1.13.9-alpine
# nginx의 기본 설정을 삭제하고 앱에서 설정한 파일을 복사
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /app/build /usr/share/nginx/html

# 80포트 오픈하고 nginx 실행
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]