FROM node:12 as builder

WORKDIR /app

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

RUN rm /usr/local/bin/yarn
RUN rm /usr/local/bin/yarnpkg && npm install -g yarn
RUN yarn set version berry

RUN yarn install

COPY . /app
RUN yarn build:prd

FROM nginx:1.13.9-alpine
# nginx의 기본 설정을 삭제하고 앱에서 ㅛㅁ구설정한 파일을 복사
RUN rm -rf /etc/nginx
COPY conf/prd /etc/nginx

# RUN rm -rf /etc/nginx/conf.d
# COPY conf.d /etc/nginx/conf.d

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /app/build /usr/share/nginx/html

# 80포트 오픈하고 nginx 실행
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]